name: Run Gitleaks on the PRIME ReportStream code-base

on:
  push:
    branches:
      - feature/lucasdze-test

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          # Fetch the full history
          fetch-depth: 0

      - name: "Run Gitleaks on a selected part of our history"
        run: .environment/gitleaks/run-gitleaks.sh  #--since '2021-08-01T00:00:00-0400'
        # with:
        #   report_format: "sarif"
        #   fail: false

      - name: Get the output from the gitleaks step
        run: |
          echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
          echo "result: ${{ steps.gitleaks.outputs.result }}"
          echo "output: ${{ steps.gitleaks.outputs.output }}"
          echo "command: ${{ steps.gitleaks.outputs.command }}"
          echo "report: ${{ steps.gitleaks.outputs.report }}"
      - name: Upload SARIF report
        if: steps.gitleaks.outputs.exitcode == 1
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.gitleaks.outputs.report }}

      # - name: "Output non-sensitive log"
      #   if: always()
      #   run: cat "gitleaks.log"
