name: Metabase Inactive users

on:
    workflow_dispatch:
    schedule:
      - cron: "13 1 1 * *"

jobs:
  alert_version_upgrade:
    name: Alert about Metabase Inactive users
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Changes
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          fetch-depth: 0
          
      - name: Get Metabase Inactive users
        shell: pwsh
        env:
            pass: ${{ secrets.MBPwd }}
            user: ${{ secrets.MBUserName }}
        run: |
            ./.github/scripts/MetabaseUsers/MBUserAPI.ps1 -key  ${{ secrets.Metabase_key }}

      - name: Decode Slack Message
        shell: pwsh
        run: |
          $SLACK_MESSAGE_Users = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:SLACK_MESSAGE_SUMMARY))
          echo $SLACK_MESSAGE_Users > SLACK_MESSAGE_Users.md
          echo "## Inactive users`n$SLACK_MESSAGE_Users" >> $env:GITHUB_STEP_SUMMARY
      
      - name: Get Inactive users
        id: users_out
        shell: bash
        run: |
          messageInactiveUsers=$(cat SLACK_MESSAGE_Users.md)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "MESSAGE_RESPONSE<<$EOF" >> $GITHUB_OUTPUT
          echo -e "$messageInactiveUsers">> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Slack Notification
        uses: ./.github/actions/notifications
        with:
          method: slack
          title: Inactive users
          message: |
            ${{ steps.users_out.outputs.MESSAGE_RESPONSE }}
          icon-emoji: ':hourglass_flowing_sand:'
          channel: cdc-reportstream-devsecops-new
  # Updated channel in slack
          webhook-url: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK_URL }}  # Updated webhook secret
          color: warning
          slackify-markdown: true
