name: Frontend

on:
  pull_request:
    branches:
      - master
      - production
  push:
    branches:
      - master

jobs:
  pre_job:
    name: Pre Job
    runs-on: ubuntu-latest
    outputs:
      has_react_change: ${{ steps.skip_check.outputs.frontend_react }}
    steps:
      - name: "Check out changes"
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: skip_check
        with:
          list-files: csv
          filters: |
            frontend_react:
              - 'frontend-react/**'

  build_frontend_react:
    name: Build Frontend React
    needs: pre_job
    if: ${{ needs.pre_job.outputs.has_react_change == 'true' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend-react

    steps:
      - name: "Check out changes"
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }} with yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: |
          yarn install

      - name: Build release (conditional check)
        if: github.ref == 'refs/heads/production'
        run: |
          yarn build:release

      - name: Build staging (conditional check)
        if: github.ref == 'refs/heads/master'
        run: |
          yarn build:staging

      - name: Build fallthrough to staging (conditional check)
        if: (!(github.ref == 'refs/heads/master' || github.ref == 'refs/heads/production'))
        run: |
          yarn build:staging
