name: Chromatic Main Branch

on:
  push:
    branches: [main]
    paths:
      - "frontend-react/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  chromatic:
    defaults:
      run:
        shell: bash
        working-directory: frontend-react
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - On Push Event
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0
      - name: Use Node.js with yarn
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version-file: "frontend-react/.nvmrc"
          cache: yarn
          cache-dependency-path: frontend-react/yarn.lock
      - name: Yarn install
        run: yarn install --immutable

      - name: Run Chromatic
        uses: chromaui/action@9f1ad414f2e282aeff674364a9098b328382103f
        with:
          workingDir: frontend-react
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # Accept all changes in main
          autoAcceptChanges: true
          exitOnceUploaded: true
