name: Release to GitHub

on:
  push:
    branches:
      - master
      - production

concurrency: ${{ github.ref }}-gh-release

jobs:
  wf_vars:
    name: Set workflow variables
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.build_vars.outputs.env_name }}
      version: ${{ steps.build_vars.outputs.version }}
      prerelease: ${{ steps.build_vars.outputs.prerelease }}
      enable_builds: 'true'
    steps:
      - name: Check out changes
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - name: Build vars
        id: build_vars
        uses: ./.github/actions/build-vars

  build_router:
    name: Build router
    needs:
      - wf_vars
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: prime-router
    steps:
      - name: Check out changes
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Build backend
        if: ${{ needs.wf_vars.outputs.enable_builds == 'true' }}
        uses: ./.github/actions/build-backend
        with:
          version: ${{ needs.wf_vars.outputs.version }}

  build_frontend:
    name: Build frontend
    needs:
      - wf_vars
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-react
    steps:
      - name: Check out changes
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Build frontend
        if: ${{ needs.wf_vars.outputs.enable_builds == 'true' }}
        uses: ./.github/actions/build-frontend
        with:
          env-name: ${{ needs.wf_vars.outputs.env_name }}
          appinsights-staging-key: ${{ secrets.APPINSIGHTS_STAGING_KEY }}
          appinsights-prod-key: ${{ secrets.APPINSIGHTS_PROD_KEY }}
          version: ${{ needs.wf_vars.outputs.version }}
          test-admin-user: ${{ secrets.TEST_ADMIN_USERNAME }}
          test-admin-password: ${{ secrets.TEST_ADMIN_PASSWORD }}
          test-sender-user: ${{ secrets.TEST_SENDER_USERNAME }}
          test-sender-password: ${{ secrets.TEST_SENDER_PASSWORD }}
          test-receiver-user: ${{ secrets.TEST_RECEIVER_USERNAME }}
          test-receiver-password: ${{ secrets.TEST_RECEIVER_PASSWORD }}

  publish_github_release:
    name: Publish to Github
    needs:
      - wf_vars
      - build_router
      - build_frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out changes
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - name: Download router artifact
        if: ${{ needs.wf_vars.outputs.enable_builds == 'true' }}
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427
        with:
          name: prime-router-build-${{ needs.wf_vars.outputs.version }}
          path: archives/
      - name: Download frontend artifact
        if: ${{ needs.wf_vars.outputs.enable_builds == 'true' }}
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427
        with:
          name: static-website-react-${{ needs.wf_vars.outputs.version }}
          path: archives/
      - name: Delete older pre-release
        if: |
          ${{ needs.wf_vars.outputs.env_name == 'staging' }} ||
          ${{ needs.wf_vars.outputs.env_name == 'prod' }}
        uses: dev-drprasad/delete-older-releases@0bf4e6748f08135170c2294f877ba7d9b633b028
        with:
          keep_latest: 0
          delete_tags: true
          delete_tag_pattern: 'pre-release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.wf_vars.outputs.version }}
          allowUpdates: true
          artifacts: "archives/*.tar.gz,LICENSE"
          prerelease: ${{ needs.wf_vars.outputs.prerelease }}
      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@f8d971b3a0059ee55b6cbd17bd7b7187dcff2d6b
        with:
          configuration: '.github/changelog_config.json'
          # Allow changelog tests in forks
          owner: 'CDCgov'
          repo: 'prime-reportstream'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update release notes
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.wf_vars.outputs.version }}
          allowUpdates: true
          body: ${{steps.build_changelog.outputs.changelog}}
          prerelease: ${{ needs.wf_vars.outputs.prerelease }}
      - name: Delete older releases
        if: ${{ needs.wf_vars.outputs.env_name == 'prod' }}
        uses: dev-drprasad/delete-older-releases@0bf4e6748f08135170c2294f877ba7d9b633b028
        with:
          keep_latest: 24
          delete_tags: false
          delete_tag_pattern: 'v-20'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
